name: release arch-x86_64

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  call:
    uses: ./.github/workflows/release.yaml
    with:
      arch: arch-x86_64
      agrrunner: ubuntu-24.04
      packages: |
        [
          "gitweb-dlagent",
          "librga-multi",
          "acestream-media-bin",
          "dri2to3-git",
          "bcm4335-firmware",
          "gl4es-git",
          "kodi-mpp-git",
          "libmali-valhall-g610-base",
          "libmali-valhall-g610-dummy",
          "libmali-valhall-g610-gbm",
          "libmali-valhall-g610-x11-gbm",
          "libmali-valhall-g610-wayland-gbm",
          "libmali-valhall-g610-x11-wayland-gbm",
          "mesa-panvk-git",
          "mesa-panfork-git",
          "mpp-git",
          "ffmpeg-mpp",
          "firefox-mpp",
          "libv4l-rkmpp-git",
          "v4l-utils-mpp",
          "sunshine-mpp-git",
          "dolphin-emu",
          "dolphin-emu-tool",
          "agr-git",
          "mpv-mpp",
          "plasma-nano",
          "plasma-bigscreen-git",
          "ctranslate2",
          "python-ctranslate2",
          "espeak-ng-git",
          "onednn",
          "onnxruntime-cpu",
          "python-onnxruntime-cpu",
          "python-piper-tts-git",
          "python-av",
          "python-faster-whisper",
          "python-sentence-stream-git",
          "python-tokenizers",
          "python-wyoming",
          "python-wyoming-faster-whisper",
          "python-wyoming-piper",
          "home-assistant-core",
          "home-assistant-hacs",
          "python-home-assistant-frontend",
          "kodi-addon-audiodecoder-2sf-git",
          "kodi-addon-audiodecoder-asap-git",
          "kodi-addon-audiodecoder-gme-git",
          "kodi-addon-audiodecoder-gsf-git",
          "kodi-addon-audiodecoder-hvl-git",
          "kodi-addon-audiodecoder-modplug-git",
          "kodi-addon-audiodecoder-ncsf-git",
          "kodi-addon-audiodecoder-nosefart-git",
          "kodi-addon-audiodecoder-openmpt-git",
          "kodi-addon-audiodecoder-organya-git",
          "kodi-addon-audiodecoder-qsf-git",
          "kodi-addon-audiodecoder-sacd-git",
          "kodi-addon-audiodecoder-sidplay-git",
          "kodi-addon-audiodecoder-snesapu-git",
          "kodi-addon-audiodecoder-ssf-git",
          "kodi-addon-audiodecoder-stsound-git",
          "kodi-addon-audiodecoder-timidity-git",
          "kodi-addon-audiodecoder-upse-git",
          "kodi-addon-audiodecoder-usf-git",
          "kodi-addon-audiodecoder-vgmstream-git",
          "kodi-addon-audiodecoder-wsr-git",
          "kodi-addon-audioencoder-flac-git",
          "kodi-addon-audioencoder-lame-git",
          "kodi-addon-audioencoder-vorbis-git",
          "kodi-addon-audioencoder-wav-git",
          "kodi-addon-game-libretro-2048-git",
          "kodi-addon-game-libretro-git",
          "kodi-addon-imagedecoder-heif-git",
          "kodi-addon-imagedecoder-mpo-git",
          "kodi-addon-imagedecoder-raw-git",
          "kodi-addon-inputstream-adaptive-git",
          "kodi-addon-inputstream-ffmpegdirect-git",
          "kodi-addon-inputstream-rtmp-git",
          "kodi-addon-peripheral-joystick-git",
          "kodi-addon-peripheral-xarcade-git",
          "kodi-addon-pvr-argustv-git",
          "kodi-addon-pvr-dvblink-git",
          "kodi-addon-pvr-dvbviewer-git",
          "kodi-addon-pvr-filmon-git",
          "kodi-addon-pvr-freebox-git",
          "kodi-addon-pvr-hdhomerun-git",
          "kodi-addon-pvr-hts-git",
          "kodi-addon-pvr-iptvsimple-git",
          "kodi-addon-pvr-mediaportal-tvserver-git",
          "kodi-addon-pvr-mythtv-git",
          "kodi-addon-pvr-nextpvr-git",
          "kodi-addon-pvr-njoy-git",
          "kodi-addon-pvr-octonet-git",
          "kodi-addon-pvr-pctv-git",
          "kodi-addon-pvr-plutotv-git",
          "kodi-addon-pvr-sledovanitv-cz-git",
          "kodi-addon-pvr-stalker-git",
          "kodi-addon-pvr-teleboy-git",
          "kodi-addon-pvr-vbox-git",
          "kodi-addon-pvr-vdr-vnsi-git",
          "kodi-addon-pvr-vuplus-git",
          "kodi-addon-pvr-waipu-git",
          "kodi-addon-pvr-wmc-git",
          "kodi-addon-pvr-zattoo-git",
          "kodi-addon-screensaver-asteroids-git",
          "kodi-addon-screensaver-asterwave-git",
          "kodi-addon-screensaver-biogenesis-git",
          "kodi-addon-screensaver-cpblobs-git",
          "kodi-addon-screensaver-greynetic-git",
          "kodi-addon-screensaver-matrixtrails-git",
          "kodi-addon-screensaver-pingpong-git",
          "kodi-addon-screensaver-pyro-git",
          "kodi-addon-screensaver-shadertoy-git",
          "kodi-addon-screensaver-stars-git",
          "kodi-addon-screensavers-rsxs-git",
          "kodi-addon-vfs-libarchive-git",
          "kodi-addon-vfs-rar-git",
          "kodi-addon-vfs-sftp-git",
          "kodi-addon-vfs-smb2-git",
          "kodi-addon-visualization-fishbmc-git",
          "kodi-addon-visualization-goom-git",
          "kodi-addon-visualization-matrix-git",
          "kodi-addon-visualization-milkdrop-git",
          "kodi-addon-visualization-milkdrop2-git",
          "kodi-addon-visualization-pictureit-git",
          "kodi-addon-visualization-projectm-git",
          "kodi-addon-visualization-shadertoy-git",
          "kodi-addon-visualization-spectrum-git",
          "kodi-addon-visualization-starburst-git",
          "kodi-addon-visualization-waveform-git",
          "tvheadend-git",
          "libdvbcsa-git"
        ]

